### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-cli-utils#3]
@muffinresearch once you gain admin rights on this repo, could you please enable Travis-CI?

**Comment by willdurand** [comment]
Let me know if this should be done by filing a bugzilla bug instead.

**Comment by muffinresearch** [comment]
@willdurand Yeah you'll need to file an issue on bugzilla, I don't see a way to enable this from settings.

**Comment by willdurand** [comment]
Ah ok, thanks. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1581784.

Re-reading the Wiki, only GitHub owners can do that now..
