### ISSUE TITLE
Configure NPM credentials

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-cli-utils#4]
@muffinresearch once the Travis CI integration is set up, could you please create 2 secret env vars in the settings to configure NPM with the addons-robot account:

- `NPM_EMAIL`
- `NPM_TOKEN`

Thanks!

**Comment by willdurand** [comment]
@muffinresearch looks like travis-ci has been enabled. You can set env vars in https://travis-ci.com/mozilla/addons-cli-utils/settings

**Comment by muffinresearch** [comment]
Credentials added.
